Fix adding a new circle as a new user
coordinape/coordinape pull request #1144
Opened 2022-07-15 20:03 UTC by sshmm

## Motivation and Context

When a user who is not a part of a circle tries to create a new circle, they create button is not responsive

## Description

There was an issue regarding the input field of protocol(org) name
![image](https://user-images.githubusercontent.com/34943689/179302162-683580a9-c4e8-4058-9125-31fed649fbdc.png)
The control props was not added to the input field in the condition of a user is not part of an org.
![image](https://user-images.githubusercontent.com/34943689/179302295-4849aaf9-89ff-4831-ad11-7d37c7c3648a.png)

## Test and Deployment Plan
Use a new wallet and try to add a circle

2022-07-16 08:45 UTC, levity commented
@crabsinger does this overlap with your fix?

2022-07-16 10:22 UTC, sshmm commented
> @crabsinger does this overlap with your fix?

#1147 is addressing a different issue if this is the one you are talking about

2022-07-18 13:24 UTC, levity approved these changes
LGTM as long as when you create a circle from an existing org, that still works

2022-07-18 17:02 UTC, crabsinger commented
@sshmm this still seems to be erroring for me (although it may be a separate issue than the one you fixed)...

On your branch in the Vercel preview, I go to https://coordinape-hg277k04e-coordinape.vercel.app/new-circle with a new address, and try to create a Circle, and I get this error:
<img width="1506" alt="Screen Shot 2022-07-18 at 10 00 11 AM" src="https://user-images.githubusercontent.com/83605543/179564130-24fa5675-5912-420a-b665-cf54889de52f.png">

2022-07-18 17:03 UTC, crabsinger requested changes
Doesn't seem to fully fix new addresses creating circles...

2022-07-19 00:19 UTC, crabsinger approved these changes
actually - seems this does resolve the bug!!!

2022-07-19 00:19 UTC, merged