Feature/admin circle page danger zone
coordinape/coordinape pull request #1262
Opened 2022-08-11 14:18 UTC by sshmm

## Motivation and Context
implements #966

## Description

1- add danger zone to circle admin page
2- add remove circle modal with remove and cancel buttons
3- on remove circle the circle will be removed and navigation to overview page happens
4- on error show snackbar error

## Test and Deployment Plan

precondition : circle admin
1- Go to circle Admin page and click remove circle button in danger zone
2a - click remove circle button in remove circle modal
Expected:
Navigation to overview page and the circle should not appear from it
2b- click cancel button
Expected:
the modal should be closed
2c- hardcode a wrong circle number and click remove
Expected:
Snackbar should appear with error

## Screenshots (if appropriate):
![Screenshot from 2022-08-11 16-05-05](https://user-images.githubusercontent.com/34943689/184154890-dc74ec3b-7cf0-4720-b57c-bcfd7ef4e784.png)

![Screenshot from 2022-08-11 16-05-30](https://user-images.githubusercontent.com/34943689/184154872-fb7c1f3b-8437-42c3-9e82-2d539d9abade.png)

2022-08-15 16:34 UTC, crabsinger commented
@sshmm can you update this branch off main and resolve the conflict, then I'll finalize review and merge.

2022-08-15 17:29 UTC, sshmm commented
> @sshmm can you update this branch off main and resolve the conflict, then I'll finalize review and merge.

done.

2022-08-15 22:30 UTC, crabsinger submitted a review, later dismissed
lgtm

2022-08-16 14:49 UTC, topocount requested changes
There are a lot of locations where information is contingent on some circle-level lookup succeeding. We should either

a) add the deleted_at clause to the table permissions in hasura
b) make sure that all queries contain this clause.

a is simpler to implement and easier to maintain.

@sshmm reach out to me if you're not sure how to do a. Here are the docs for it: https://hasura.io/docs/latest/auth/authorization/permission-rules/#row-level-permissions

2022-08-16 20:29 UTC, sshmm commented
@crabsinger could you merge https://github.com/sshmm/coordinape/tree/AdminCirclePage_DangerZone to this branch because I don't have access to this branch after you rebased it

2022-08-18 17:33 UTC, topocount commented on hasura/metadata/databases/default/tables/public_circles.yaml
> +              _is_null: true
This actually breaks functionality for user-level members and fails to return circles a user is not a member in but is within the org. These entries from our test seed are missing in the UI: 
![image](https://user-images.githubusercontent.com/17910833/185457593-7bea160c-7e93-4bdf-bb3a-db8b228d957f.png)

I recommend this instead:

```suggestion
      - organization:
          circles:
            users:
              _and:
              - profile:
                  id:
                    _eq: X-Hasura-User-Id
              - deleted_at:
                  _is_null: true
      - deleted_at:
          _is_null: true

```

2022-08-19 16:02 UTC, topocount approved these changes
looks good! passes the test suite locally for me so I'll go ahead and merge it

2022-08-19 16:11 UTC, merged