Admin Settings: 1) Fixed payments vault field,  2) Token name for CSV export field
coordinape/coordinape pull request #1268
Opened 2022-08-13 05:35 UTC by wingfeatherwave

<img width="1407" alt="Screen Shot 2022-08-12 at 3 38 48 PM" src="https://user-images.githubusercontent.com/100873710/184470025-506dce93-4f55-4b84-b9c3-79d3d22f9d3e.png">
<img width="1396" alt="Screen Shot 2022-08-12 at 3 20 18 PM" src="https://user-images.githubusercontent.com/100873710/184470026-1694ca4d-80c6-430f-ac72-789d31d6e427.png">
 Motivation and Context

References: https://www.notion.so/coordinape/Cannot-use-Simple-Token-Vault-for-Fixed-payments-ff90ebe6bbc94beba09d61dd17c6cdf2

Problem: The Fixed Payment Vault Token autocomplete field was overloaded and confusing 
Solution: 

* Break up fixed payments token fields into two fields
* Use stitches select component to show available vaults to select and effectively enable fixed payments
* new column: circle.fixed_payment_vault_id
* repurpose fixed_payment_token_type for use in csv export only
* when vault is selected, csv token is disabled and uses the vault token...
* otherwise, when vault is not selected, csv token can be named whatever the heck you like

@zashton you can use this `<Select>`  component for vault selection on the distributions page

2022-08-14 14:43 UTC, zashton approved these changes
made some minor updates, new input field works for me.

2022-08-15 16:20 UTC, zashton commented
@wingfeatherwave btw for the select theres no disabled state and the ability to set labels like other input components

2022-08-15 16:45 UTC, crabsinger commented
Tested the migrations locally and they look good (both up and down)

2022-08-15 17:02 UTC, crabsinger requested changes

2022-08-15 17:41 UTC, crabsinger approved these changes

2022-08-15 18:23 UTC, merged