Allow full decimals for allocation table and claims page
coordinape/coordinape pull request #1361
Opened 2022-09-19 13:32 UTC by zashton

## Motivation and Context

Update so asto  handle token numbers that need more decimals (like WBTC or YFI).

## Description

Use commify to truncate until the last significant number instead of hardcoded of 2 decimals point

## Test and Deployment Plan

Distribution page unit test should pass.

## Screenshots (if appropriate):

<img width="1367" alt="image" src="https://user-images.githubusercontent.com/17747090/191024601-8bbc4ba1-c9cf-4ff3-89bc-71951ca0f365.png">
<img width="1353" alt="image" src="https://user-images.githubusercontent.com/17747090/191025252-14f3f050-a66a-4b57-b929-5cc724918989.png">

## Reviewers

@topocount @levity @crabsinger 

## Related Issue

https://www.notion.so/coordinape/78924b82ebe4445cbe20f586cdcb2795?v=bbf298c4fee34b5ea4eb18db638676bf&p=81b5681adae94c448482df112727e191&pm=s

2022-09-19 17:36 UTC, crabsinger approved these changes

2022-09-19 17:57 UTC, levity requested changes
I'm not sure this is a good change as-is. With DAI and USDC, we don't need to show this many decimal places. What would be ideal is a "round to significant figures" function that is smart about showing extra decimal places only when the value would be rounded to 0 otherwise. 

But maybe a simpler rule would work, something like "round to 2 places if value is greater than 10, and to 4 places otherwise."

2022-09-20 13:48 UTC, zashton commented
> I'm not sure this is a good change as-is. With DAI and USDC, we don't need to show this many decimal places. What would be ideal is a "round to significant figures" function that is smart about showing extra decimal places only when the value would be rounded to 0 otherwise.
> 
> But maybe a simpler rule would work, something like "round to 2 places if value is greater than 10, and to 4 places otherwise."

updated

2022-09-21 00:06 UTC, levity approved these changes

2022-09-21 02:36 UTC, merged