Claim Tokens Button on MobileHeader
coordinape/coordinape pull request #1585
Opened 2022-10-27 18:11 UTC by yahiamarzouk

## Motivation and Context

Added the Claim tokens Button on mobile UI

## Description

## Test and Deployment Plan

## Screenshots (if appropriate):

## Reviewers

## Related Issue

#1488

2022-11-01 21:36 UTC, crabsinger requested changes

2022-11-01 21:36 UTC, crabsinger commented on src/components/MainLayout/MobileHeader.tsx
> +                {isFeatureEnabled('vaults') && (
@yahiamarzouk I think we should follow the logic from the [main header](https://github.com/coordinape/coordinape/blob/main/src/components/MainLayout/MainHeader.tsx#L39) and only show this button if there are claims, not always:

```suggestion
          {isFeatureEnabled('vaults') && showClaimsButton && (
```

2022-11-07 13:04 UTC, levity requested changes
can you please move the button so that it's at the top of the menu? and make sure the left edge of the button is aligned with the other items in the list

2022-11-07 23:53 UTC, wingfeatherwave commented
@levity @yahiamarzouk I"m updating the mobile menu to not look like trash, which will fix the alignment issues described.  I will merge this code into my branch to avoid the conflicts.

2022-11-07 23:53 UTC, closed without merging