Add Pgives schema
coordinape/coordinape pull request #1658
Opened 2022-11-14 14:48 UTC by zashton

## Motivation and Context

Updated schema in preparation for pgive stuff.

## Description

Additional table and columns in epoch table to index pgive data.

2022-11-14 15:08 UTC, levity commented
I think that for this sort of data, which isn't used for the core app, it would be better to have it in a separate table that has a foreign key into epochs. This will be more flexible for future changes for permissions, performance optimizations, etc.

2022-11-14 15:10 UTC, levity commented
Also, can you create a separate PR just with the changes to the schema & metadata that aren't related to your changes? Thanks!

2022-11-15 12:07 UTC, zashton commented
> I think that for this sort of data, which isn't used for the core app, it would be better to have it in a separate table that has a foreign key into epochs. This will be more flexible for future changes for permissions, performance optimizations, etc.

have created a seperate table and added relationship to epochs

2022-11-29 19:17 UTC, levity commented on hasura/metadata/databases/default/tables/public_epoches.yaml
> +  - name: epoch_pgive_data
can you change the relation name to just `pgive_data`? no need to repeat `epoch_` when you're already starting from an epoch

2022-11-29 19:19 UTC, levity requested changes
Just the one rename; all else looks good

2022-12-03 01:51 UTC, levity approved these changes

2022-12-04 12:09 UTC, merged