Create profiles with names mutations
coordinape/coordinape pull request #1735
Opened 2022-12-05 15:11 UTC by sshmm

## Motivation and Context

resolves #1395

## Description

1- Add a modal to ask users to enter a profile name that will be used in all circles
2- Change createusers mtations 'manual-address-entry' to check if the names exists in profiles and nominees
3- create users and profiles as follows:
 - if the user has a profile without a name the entered name will be the profile name
 - if the user doesn't have a profile, create a profile with that name
 - if the name exists for other addresses inform the user
 4- create Nominee only if the nominee name is not used by other nominees or users

## Test and Deployment Plan
### Test 1
1- Log in to coordinape
expected:
a modal should appear to enter user name and only accepts unique names

### Test 2
1- Create a nominee with a unique name
2- try to add user with that name
expected:
you should get an error about the situation

### Test 3
1- complete the vouching for the nominee in Test 2
expected: a profile with the nominee name should be added

### Test 4
1- create a user with a new name
expected: a profile with the user name should be added

### Test 5
1- create a user with a name in profiles table
expected: you should get an error

## Screenshots (if appropriate):
![image](https://user-images.githubusercontent.com/34943689/205672032-181bb5ca-1f88-4c5f-aa7f-1e3b7d68e0f3.png)

![Screenshot from 2022-12-05 15-40-05](https://user-images.githubusercontent.com/34943689/205670847-2b9571f1-3ea0-432c-97c7-114204e6746c.png)

![Screenshot from 2022-12-04 23-25-34](https://user-images.githubusercontent.com/34943689/205670879-1249aea0-8011-4963-a4e5-a7e9971aebe6.png)

2022-12-07 12:47 UTC, zashton requested changes
nice work on the profile name changes, left a few suggestions.

2022-12-07 12:47 UTC, zashton commented on api/hasura/actions/_handlers/createUsers.ts
> +  const { profiles } = await adminClient.query(
You probably can save on the query call if you merge the create & update profile mutation into an upsert like this. Think this should work the same.

```
import { profiles_constraint, profiles_update_column } from '../../../../api-lib/gql/__generated__/zeus';

const createProfilesMutations = adminClient.mutate({
    insert_profiles:[
      {
        objects: newUsers.map( user => {
          return {
            address: user.address.toLowerCase(),
            name: user.name,
          }
        }),
        on_conflict: {
          constraint: profiles_constraint.profiles_address_key,
          update_columns: [profiles_update_column.name],
          where: {
            name: {_is_null: true}
          }
        }
      },
      {
        returning: {
          id: true,
        }
      }
    ]
  },
  {
    operationName: 'createUsers_createProfiles',
  });
  ```

2022-12-07 12:47 UTC, zashton commented on api/hasura/actions/_handlers/createUserMutation.ts
> +    createProfileMutation = await adminClient.mutate(
its possible to do it as an upsert as well here

2022-12-07 12:47 UTC, zashton commented on src/lib/zod/index.ts
> +    name: z.string(),
should we impose a character limit ?

2022-12-07 15:56 UTC, sshmm commented on api/hasura/actions/_handlers/createUsers.ts
> +                  { name: { _eq: user.name } },
I am using citext for names so ilike is not necessary

2022-12-07 23:27 UTC, levity reviewed
Oops! I left a bunch of comments 2 days ago but never submitted the review. If anything I've said since then conflicts with a comment here, ignore the comment. :)

2022-12-08 12:04 UTC, zashton submitted a review, later dismissed
Went through all the test cases, works with no issues. 👍

2022-12-08 12:06 UTC, zashton commented
@sshmm note that all the e2e cypress tests are failing

2022-12-15 04:23 UTC, zashton submitted a review, later dismissed

2022-12-20 19:53 UTC, levity approved these changes
nice work! sorry it took so long to get thru review 😅

2022-12-20 19:55 UTC, merged