store profile data globally
coordinape/coordinape pull request #1994
Opened 2023-03-01 12:09 UTC by levity

this is for determining whether the user is a member of a given org without adding additional requests. it will also help moving away from Recoil

2023-03-01 12:09 UTC, levity commented
Current dependencies on/for this PR:
* main
  * **PR #1993** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1993" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #1994** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1994" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a>  👈
      * **PR #1995** <a href="https://app.graphite.dev/github/pr/coordinape/coordinape/1995" target="_blank"><img src="https://static.graphite.dev/graphite-32x32.png" alt="Graphite" width="10px" height="10px"/></a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/coordinape/coordinape/1994?utm_source=stack-comment).

2023-03-01 12:14 UTC, levity commented on src/features/auth/store.ts
> +import type { QueryManifest } from 'hooks/useApiBase';
i don't love the dependency chain here... but i could probably resolve it by pulling fetchManifest into this feature

2023-03-03 05:20 UTC, CryptoGraffe approved these changes
I approved but I'm nervous about storing the results of the profile query w/ no invalidation pattern for it. Would rather just store the id and/or addr

2023-03-03 05:57 UTC, levity commented
In persistent local storage, I’m storing only the ID and address. This is
storing the results of the profile query in Zustand only until the page is
closed/reloaded

On Fri, Mar 3, 2023 at 1:20 PM Graffe ***@***.***> wrote:

> ***@***.**** approved this pull request.
>
> I approved but I'm nervous about storing the results of the profile query
> w/ no invalidation pattern for it. Would rather just store the id and/or
> addr
> ------------------------------
>
> In src/features/auth/useFinishAuth.ts
> <https://github.com/coordinape/coordinape/pull/1994#discussion_r1124003744>
> :
>
> >
>  export const useFinishAuth = () => {
>    const { showError } = useToast();
>    const { fetchManifest } = useApiBase();
>    const logout = useLogout();
> +  const [savedAuth, setSavedAuth] = useSavedAuth();
> +  const web3Context = useWeb3React();
> +  const setProfile = useAuthStore(state => state.setProfile);
>
> so this will only get updated at login afaict. If you are going to rely on
> this for state beyond the profile_id , it will be stale. Am I missing a
> link here? Seems like we could just store the profile_id and then org
> memberships or whatever else could be handled through an invalidateable
> react query.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/coordinape/coordinape/pull/1994#pullrequestreview-1323067026>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABPJA3RJG46MGQ7NEUGOGDW2F5STANCNFSM6AAAAAAVL6375U>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-03 05:58 UTC, levity commented
It runs every time the page is loaded from scratch. I know the “login”
naming is probably misleading, but this runs whether you’re logging in for
the first time or reusing an auth token that is still valid

On Fri, Mar 3, 2023 at 1:57 PM Lawrence Wang ***@***.***> wrote:

> In persistent local storage, I’m storing only the ID and address. This is
> storing the results of the profile query in Zustand only until the page is
> closed/reloaded
>
> On Fri, Mar 3, 2023 at 1:20 PM Graffe ***@***.***> wrote:
>
>> ***@***.**** approved this pull request.
>>
>> I approved but I'm nervous about storing the results of the profile query
>> w/ no invalidation pattern for it. Would rather just store the id and/or
>> addr
>> ------------------------------
>>
>> In src/features/auth/useFinishAuth.ts
>> <https://github.com/coordinape/coordinape/pull/1994#discussion_r1124003744>
>> :
>>
>> >
>>  export const useFinishAuth = () => {
>>    const { showError } = useToast();
>>    const { fetchManifest } = useApiBase();
>>    const logout = useLogout();
>> +  const [savedAuth, setSavedAuth] = useSavedAuth();
>> +  const web3Context = useWeb3React();
>> +  const setProfile = useAuthStore(state => state.setProfile);
>>
>> so this will only get updated at login afaict. If you are going to rely
>> on this for state beyond the profile_id , it will be stale. Am I missing a
>> link here? Seems like we could just store the profile_id and then org
>> memberships or whatever else could be handled through an invalidateable
>> react query.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/coordinape/coordinape/pull/1994#pullrequestreview-1323067026>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AABPJA3RJG46MGQ7NEUGOGDW2F5STANCNFSM6AAAAAAVL6375U>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

2023-03-06 17:47 UTC, CryptoGraffe requested changes
I'm removing approval until the invalidation stuff is sorted

2023-03-07 02:43 UTC, levity commented
@CryptoGraffe invalidation stuff has been addressed

2023-03-07 04:30 UTC, CryptoGraffe approved these changes

2023-03-07 04:36 UTC, merged