Quick toggle menu of orgs in nav
coordinape/coordinape pull request #2104
Opened 2023-04-19 20:24 UTC by wingfeatherwave

Make it easier to switch orgs in the nav without having to navigate to "home"

<img width="323" alt="Screenshot 2023-04-19 at 1 16 14 PM" src="https://user-images.githubusercontent.com/100873710/233189899-dbff7ede-74ac-47b5-acce-5556e121bf22.png">

2023-04-19 23:30 UTC, levity requested changes

2023-04-19 23:30 UTC, levity commented on src/features/nav/NavOrgs.tsx
> +                key={'orgLabel'}
same thing here: is the key needed? if so, use normal quotes pls

2023-04-20 17:36 UTC, wingfeatherwave commented on src/features/nav/NavCircles.tsx
> +                  <Dots nostroke />
I'm OK with the chevron.  Thought the dots were fun...  But if it's potentially confusing, it's probably not worth it.  Changed to chevron.

2023-04-20 17:37 UTC, wingfeatherwave commented on src/features/nav/NavCircles.tsx
> +            key={'circlesLabel'}
key not needed.  removed

2023-04-24 16:49 UTC, crabsinger commented
@wingfeatherwave I'm seeing some curious flickering behavior in the currently selected Org "Coordinape" in this case - captured in this video - when opening and closing the menu.

It looks like I see a "Co" without an image flicker in place during the transition.



https://user-images.githubusercontent.com/83605543/234063225-2debc3e1-d8c4-4afa-a807-ef8328aa5133.mov

2023-04-25 21:08 UTC, wingfeatherwave commented
@crabsinger I've fixed the flicker.  It's not as elegant of code, but it seems to work

2023-05-02 22:12 UTC, closed without merging