Created the useApeRouter and useVaultWrapper hooks
coordinape/coordinape pull request #303
Opened 2021-11-17 08:33 UTC by Too-Far

2021-11-17 09:41 UTC, Niraj-Kamdar requested changes

2021-11-17 09:41 UTC, Niraj-Kamdar commented on src/utils/contracts.ts
> +          .address,
We don't deploy apeVaultWrapper but use apeVaultFactory to create apeVaultWrapper. So, we will be initialising this on runtime dynamically.

2021-11-30 15:35 UTC, levity commented
@Niraj-Kamdar I upgraded the Infura account being used here to have access to archive state, & am re-running the CI job

2021-12-01 03:44 UTC, levity commented
wooot that worked 🎉

2021-12-01 08:14 UTC, merged