Feature: Percentage based vouching
coordinape/coordinape pull request #316
Opened 2021-11-23 18:15 UTC by Caranell

Issue: #268

2021-11-23 20:31 UTC, f1lander approved these changes
LGTM

2021-11-23 20:31 UTC, f1lander approved these changes
LGTM

2021-11-23 20:46 UTC, f1lander requested changes

2021-11-23 20:46 UTC, f1lander commented on src/pages/VouchingPage/NewNominationModal.tsx
> +    } ${(circle.nomination_days_limit || 0) > 1 ? 'days' : 'day'}. ${
Can pull out all the conditional to separate variable to do not nest all of them into a string literal? and there is no needed to put `|| 0` if you cast to `Number(circle.nomination_days_limit)` atomically if the value is `undefined or null` value would be a `NaN`

`const nominationdaysLimit = Number(circle.nomination_days_limit) > 1 ? 'days' : 'day'`

2021-11-23 20:50 UTC, f1lander approved these changes
LGTM

2021-11-23 20:56 UTC, f1lander approved these changes
LGTM

2021-11-23 21:02 UTC, f1lander commented on src/components/FormRadioGroup/FormRadioGroup.tsx
> +    <div className={classes.centered}>
Meanwhile we do not decide to change out style base tools can we keep using the components that material-ui offer to us? for example, this is equivalent to use `Box` thats creates a `div` by default but an be overried if you wish to another semantic component like `span`, more info here: https://react-hook-form.com/api/useformstate/

`import { Box } from '@material-ui/core`

`<Box justifyContent="center">`

2021-12-06 21:11 UTC, exrhizo requested changes
I am putting this with request changes because we can't merge this until the backend change is merged.

Appreciate you looking at this.

2022-01-21 17:21 UTC, crabsinger commented
I'll close this PR until someone wants to look into it more or I hear back from @Caranell .

2022-01-21 17:21 UTC, closed without merging