feat: add support for mock vault
coordinape/coordinape pull request #372
Opened 2021-12-20 06:17 UTC by Niraj-Kamdar

2021-12-20 18:23 UTC, levity commented on hardhat/hardhat.config.ts
> +if (process.env.TEST) {
```suggestion
if (process.env.TEST || process.env.CI) {
```

2021-12-29 18:23 UTC, exrhizo requested changes

2021-12-29 18:23 UTC, exrhizo commented on .env.example
> +ADMIN_ADDRESS=0x0
There is a vault owner and a circle admin in the contracts - rename this to be more specific
`HH_OWNER_ADDRESS` for example

2021-12-29 18:23 UTC, exrhizo commented on hardhat/scripts/deploy/00-mock-yearn/03-mock-yvyfi-deploy.ts
> +  });
These deploy scripts aren't in alignment with the engineering principle of `Don't Repeat Yourself`

2021-12-29 18:23 UTC, exrhizo commented on hardhat/package.json
> +    "@nomiclabs/hardhat-ganache": "^2.0.1",
We pin dependencies,
https://betterdev.blog/pin-exact-dependency-versions/

2022-01-02 20:13 UTC, exrhizo reviewed
@levity would be in a better place to approve this - although the tests are failing in github, so that is something to fix

2022-01-05 18:29 UTC, levity approved these changes

2022-01-05 19:52 UTC, merged