Updated Tooltips on Circle Admin page
coordinape/coordinape pull request #452
Opened 2022-01-22 04:20 UTC by teeolendo

Closes #428 by updating the Tooltip Component to accept a custom styling prop and moved the Add Circle button to the top right nav.

2022-01-24 04:09 UTC, levity requested changes
In addition to the line items, please make sure that the new info icons' size, vertical alignment, & spacing from text matches the Settings and Add Circle buttons' icons

2022-01-24 10:58 UTC, exrhizo reviewed
I agree w/ Lawrence, the info icon ought to match the add circle circle size, which might be too small...

Also noticing that as edax has started us on the path to using stitches, it might not be worth doing much to perfect the design, but I also notice that the info box fades in and out subtly in Ivy's design.

2022-01-24 18:55 UTC, teeolendo commented on src/pages/AdminPage/AdminPage.tsx
> +                    leaveDelay={2000}
@ivyquinzel would you be ok with 500ms instead of 2secs?

2022-01-24 19:42 UTC, ivyquinzel commented
As long as the user has enough time to click on the link inside the tool tip
On Jan 24, 2022, 11:55 -0700, Tony Olendo ***@***.***>, wrote:
> @teeolendo commented on this pull request.
> In src/pages/AdminPage/AdminPage.tsx:
> > @@ -473,7 +501,16 @@ const AdminPage = ({ legacy }: { legacy?: boolean }) => {
>                 variant="contained"
>                 color="primary"
>                 size="small"
> -                startIcon={<PlusCircleIcon />}
> +                endIcon={
> +                  <ApeInfoTooltip
> +                    iconTheme={classes.infoIcon}
> +                    enterNextDelay={1}
> +                    placement="bottom"
> +                    leaveDelay={2000}
> @ivyquinzel would you be ok with 500ms instead of 2secs?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> Triage notifications on the go with GitHub Mobile for iOS or Android.
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2022-01-25 07:13 UTC, levity approved these changes
looks good!

2022-01-25 13:51 UTC, merged