Adding Tooltip
coordinape/coordinape pull request #549
Opened 2022-02-16 16:41 UTC by MarcogodoyV

Simple addition of tooltips for the header and the stepper fix #427 (basic implementation with modification of ApeInfoTooltip component to popup a modal when user is in mobile devices)

2022-02-17 00:05 UTC, crabsinger commented
@f1lander @teeolendo any additional feedback on this or good to merge?

2022-02-22 22:44 UTC, levity requested changes
The tooltips work great on both desktop & mobile. Nice work! Just a few minor changes needed.

2022-02-22 22:44 UTC, levity commented on src/pages/AllocationPage/AllocationPage.tsx
> +  icon: {
this doesn't appear to be used in this file

2022-02-22 22:44 UTC, levity commented on src/pages/AllocationPage/AllocationPage.tsx
> +          Reward your teammates in the circle by sending them GIVE tokens.
instead of hardcoded 
```suggestion
          Reward your teammates in the circle by sending them {selectedCircle.tokenName} tokens.
```

2022-02-22 22:44 UTC, levity commented on src/pages/AllocationPage/AllocationEpoch.tsx
> +          allocate GIVE tokens to one another.
```suggestion
          allocate {selectedCircle.tokenName} tokens to one another.
```

2022-02-22 22:44 UTC, levity commented on src/pages/AllocationPage/AllocationEpoch.tsx
> +  icon: {
this doesn't appear to be used in this file

2022-02-23 03:37 UTC, MarcogodoyV commented
@levity I applyed the changes you ask me to do, but I don't know if I did the steps well here in GitHub (I added 2 new commits to the PR), it's the first time I do this. If there's a better way to do it I'll appreciate any recommendation.  Thanks for the review!

2022-02-23 20:23 UTC, levity approved these changes

2022-02-23 20:24 UTC, levity commented on src/pages/AllocationPage/AllocationPage.tsx
> +  icon: {
@MarcogodoyV just to be clear, i was only referring to the `icon` styles, so you didn't have to remove `learnMore` as well. but if it still looks good, that's ok too :)

2022-02-23 20:30 UTC, merged

2022-02-23 20:31 UTC, levity commented
@MarcogodoyV congrats on your first code commit! 🎉