Standardize backend naming
coordinape/coordinape pull request #582
Opened 2022-03-02 16:17 UTC by topocount

2022-03-03 05:15 UTC, zashton commented
realised the current linting doesn't include api-lib folder , maybe we can add that as well.

2022-03-04 10:23 UTC, zashton requested changes
Requires a `yarn generate` to be able to run the hasura console.

2022-03-04 10:23 UTC, zashton commented on hasura/metadata/actions.graphql
> +  id: Int!
Would just need `id` for this `CreateCircleResponse`

2022-03-04 10:39 UTC, zashton commented on hasura/metadata/actions.graphql
>    address: String!
not sure how the `address` came back, we removed it during the address spoofing fix

2022-03-04 20:00 UTC, CryptoGraffe approved these changes
Looks good to me. Thanks for doing all this.

2022-03-05 03:10 UTC, zashton approved these changes
All good, thanks for doing this ! , lgt hasura-next

2022-03-05 05:31 UTC, merged