implement createCircle mutation in FE
coordinape/coordinape pull request #646
Opened 2022-03-17 05:45 UTC by CryptoGraffe

This also:
* Makes a number of columns that seemed non-nullable actually non-nullable to match the typescript interfaces in frontend
* removes HASURA_ENABLED flag in FE since we want to default to using it and delete the old code

Of note:
The old front end had some differences with create circle that are currently not carried forward, and warrant discussion:
* the `uxresearchJson` that is part of createCircle
* the `captcha_token` and server side verification of such
* the `address` field was passed in by client before

Test plan:
* Create a circle in the UI

2022-03-17 09:21 UTC, zashton commented
> Fixes: #629
> 
> This also:
> 
> * Makes a number of columns that seemed non-nullable actually non-nullable to match the typescript interfaces in frontend
> * removes HASURA_ENABLED flag in FE since we want to default to using it and delete the old code
> 
> Of note: The old front end had some differences with create circle that are currently not carried forward, and warrant discussion:
> 
> * the `uxresearchJson` that is part of createCircle - I think this includes the support email? I'm not 100% sure yet.
> * the `captcha_token` and server side verification of such
> * the `address` field was passed in by client before
> 
> Test plan:
> 
> * Create a circle in the UI

1. The uxresearch field was requested to be removed based on 

https://www.notion.so/coordinape/Onboarding-Usability-Testing-Results-693be58b07454565aa4640966094edef#32b8261d52c4480bab239097d261daa1

2. captcha token had to be removed so circles can be created via API without going through a frontend.

3. Previously a user could create a circle without having a user record in the DB, hence it was passing the address (validated with signature) . Our current backend requires the user to have a profile record before creating a circle so the address is not necessary now.

2022-03-17 18:35 UTC, levity approved these changes

2022-03-19 17:44 UTC, CryptoGraffe commented on src/lib/gql/mutations.ts
> +  // TODO: these two args are no longer used in the hasura backend mutation, should we remedy this?
its removed now but changed to a contact filed

2022-03-21 14:22 UTC, zashton requested changes
main issue is when protocol is selected during create circle validation fails, otherwise its all good.

2022-03-22 02:35 UTC, topocount commented on src/pages/CreateCirclePage/CreateCirclePage.tsx
> +            const newCircle = await createCircle({ ...params });
@zashton I think this is an issue with the zod validation, where it isn't logically identical to how laravel works right now: 
https://github.com/coordinape/coordinape-backend/blob/09c921ba25679451132a5c30852f4a522fd7cbc9/app/Http/Requests/CreateCircleRequest.php#L73-L74

As I understand it, either is required if the other isn't present, but this isn't and XOR gate where if one is present the other cannot be

2022-03-22 02:39 UTC, zashton commented on src/pages/CreateCirclePage/CreateCirclePage.tsx
> +            const newCircle = await createCircle({ ...params });
Yeah my bad, told @CryptoGraffe its a good idea to remove that part of the zod validation and ignore the `name` field if its sent together with the `protocol_id`

2022-03-22 04:24 UTC, CryptoGraffe commented on src/lib/gql/mutations.ts
> +        id: true,
ok

2022-03-22 04:25 UTC, CryptoGraffe commented on src/pages/CreateCirclePage/CreateCirclePage.tsx
> +            const newCircle = await createCircle({ ...params });
Ok i fixed this enough to make this work. Topo has a more thorough PR.

2022-03-22 04:32 UTC, CryptoGraffe commented on hasura/migrations/default/1647493316251_alter_table_public_circles_alter_column_created_at/down.sql
> +alter table "public"."circles" alter column "created_at" drop not null;
ok i did this, thanks for the tip

2022-03-22 04:33 UTC, CryptoGraffe commented
Ok @topocount and @zashton I fixed the validation error, which led to me cleaning up a bunch of error handling so its all 100% centralized. I was unhappy with the zod error making it back to the UI.

2022-03-22 05:30 UTC, zashton approved these changes
validation issue is fixed lgtm

2022-03-22 05:43 UTC, merged