Mock of Claim Funds UI
coordinape/coordinape pull request #795
Opened 2022-04-19 02:48 UTC by teeolendo

This PR contains the mock UI of the claims component. To view the button, add `REACT_APP_FEATURE_FLAG_VAULTS=true` to your .env

Added:
- Radix UIs Popover component
- Claims component that collocates the entire claims feature
- Radix UIs Icons package - wasn't sure if to start using this seeing as we are moving away from Material.

2022-04-20 18:08 UTC, levity requested changes

2022-04-20 18:08 UTC, levity commented on src/stitches.config.ts
> +      lighterGray: '#E5E5E5',
can you reuse `lightBackground` instead?

2022-04-20 18:08 UTC, levity commented on src/stitches.config.ts
> +      darkGray: '#555555',
use `text` or `secondary` instead

2022-04-20 18:08 UTC, levity commented on src/ui/Button/Button.tsx
> +      claimFunds: {
i think this should be defined in Claims rather than be a Button variant--the name suggests to me that it isn't that reusable

2022-04-20 18:08 UTC, levity commented on src/ui/Button/Button.tsx
> +        fontWeitght: '$bold',
```suggestion
        fontWeight: '$bold',
```

2022-04-20 18:08 UTC, levity commented on src/components/MainLayout/MainHeader.tsx
> +                  <Suspense fallback={<span />}>{/* <CircleNav /> */}</Suspense>
?

2022-04-20 18:08 UTC, levity commented on src/components/MainLayout/MainHeader.tsx
> +      {isVaultsEnabled && hasClaims && (
you can remove ReceiveInfo above; this is intended to replace that

2022-04-20 18:08 UTC, levity commented on src/components/Claims/index.tsx
> +import PopOver from 'ui/Popover';
```suggestion
import Popover from 'ui/Popover';
```

2022-04-20 18:08 UTC, levity commented on src/components/Claims/index.tsx
> +import { ClaimCard } from 'components/ClaimCard/ClaimCard';
maybe move the ClaimCard component into this folder?

2022-04-22 10:46 UTC, closed without merging

2022-04-22 10:47 UTC, teeolendo commented
Feature is no longer supported. Claims will now be a full page.