Allow Circle API keys to call updateAllocations action
coordinape/coordinape pull request #956
Opened 2022-05-25 03:12 UTC by META-DREAMER

## Motivation and Context

Since we use custom actions for updating user allocations, we need to adjust the auth and business logic in the action handler to account for API keys that have the `update_pending_token_gifts` permission.

## Description

Created a new action request body validator for testing if API keys have certain permissions in a standardized / explicit way.

## Test and Deployment Plan

1. Create a circle API key with the `update_pending_token_gifts` permission.
2. Use the API key to call the `updateAllocations` mutation for that circle and ensure it succeeds
3. Call the same mutation but for a different circle and ensure it fails.
4. Create another circle API key without the `update_pending_token_gifts` permission
5. Use the API key to call the `updateAllocations` mutations and ensure it fails.

## Reviewers

@topocount 

## Related Issue

#887

2022-05-25 08:09 UTC, zashton requested changes
getting this error when trying to run updateAllocations with api key,
this had the same issue similar as #955 as well regarding the `circle_id` parsing

```json
{
  "errors": [
    {
      "extensions": {
        "details": [
          {
            "path": [],
            "code": "invalid_union",
            "unionErrors": [
              {
                "name": "ZodError",
                "issues": [
                  {
                    "received": "undefined",
                    "path": [
                      "session_variables",
                      "x-hasura-user-id"
                    ],
                    "code": "invalid_type",
                    "message": "Required",
                    "expected": "string"
                  },
                  {
                    "received": "api-user",
                    "path": [
                      "session_variables",
                      "x-hasura-role"
                    ],
                    "code": "invalid_type",
                    "message": "Expected user, received api-user",
                    "expected": "user"
                  },
                  {
                    "received": "undefined",
                    "path": [
                      "session_variables",
                      "x-hasura-address"
                    ],
                    "code": "invalid_type",
                    "message": "Required",
                    "expected": "string"
                  }
                ]
              },
              {
                "name": "ZodError",
                "issues": [
                  {
                    "received": "undefined",
                    "path": [
                      "input",
                      "payload",
                      "user_id"
                    ],
                    "code": "invalid_type",
                    "message": "Required",
                    "expected": "number"
                  }
                ]
              }
            ],
            "message": "Invalid input"
          }
        ],
        "code": "422"
      },
      "message": "Invalid input: Invalid input (undefined)"
    }
  ]
}
```

2022-05-26 03:26 UTC, zashton approved these changes
works for me now 👍

2022-06-09 20:35 UTC, META-DREAMER commented
@zashton could you re-approve the PR please? Had to rebase

2022-06-10 01:20 UTC, zashton approved these changes

2022-06-10 08:58 UTC, merged